### ISSUE TITLE
Exit error and log format formatting error

### ISSUE THREAD

**Issue by csmasterpath2023** [filecoin-station/voyager#8]
[voyager.txt](https://github.com/filecoin-station/voyager/files/15281023/voyager.txt)

**Comment by juliangruber** [comment]
Could it be you're running many Station Core instances on a single IP?

**Comment by juliangruber** [comment]
What do you mean by "log format formatting error"?

**Comment by csmasterpath2023** [comment]
Yes, but my computer has multiple IPs

**Comment by csmasterpath2023** [comment]
Some of the logs may not be as beautiful, haha, but it doesn't seem important
~~~
  '{"type":"jobs-completed","total":2,"modules":{"voyager/main":2}}\n' +
    '{"type":"activity:info","module":"voyager/main","message":"Voyager benchmarking started"}',
  stderr: '[2024-05-11T00:20:10Z INFO  zinniad] Starting zinniad with config CliArgs { wallet_address: "0x59D1dAB05395B4f298e185Cc4b8301cdF0178050", station_id: "302a300506032b65700321006dc4a83f5f9e9e2092b8636c3f4610562d0791c2bec2c7a8501d51924b07810f", state_root: "/home/node/.local/state/filecoin-station-core/modules/zinnia", cache_root: "/home/node/.cache/filecoin-station-core/modules/zinnia", files: ["voyager/main.js"] }\n' +
    '[2024-05-11T00:20:10Z INFO  lassie] Starting Lassie Daemon\n' +
    '[2024-05-11T00:20:10Z INFO  lassie] Lassie Daemon is listening on port 36315\n' +
    '[2024-05-11T00:20:10Z INFO  zinniad] Starting module file:///home/node/.cache/filecoin-station-core/sources/voyager/main.js\n' +
    '[2024-05-11T00:20:11Z INFO  module:voyager/main] Running prod benchmark...\n' +
    '[2024-05-11T00:20:11Z INFO  module:voyager/main] Testing /ipfs/bafybeibxq42wx4iutyqlgumnrlkahnccaxmm3erzvij4vwkha6viapo6li/segmentNo10.ts...\n' +
    '[2024-05-11T00:20:15Z ERROR zinniad] DOMException: The signal has been aborted\n' +
    '        at new DOMException (ext:deno_web/01_dom_exception.js:115:20)\n' +
    '        at AbortSignal.[[[signalAbort]]] (ext:deno_web/03_abort_signal.js:134:14)\n' +
    '        at AbortController.abort (ext:deno_web/03_abort_signal.js:279:30)\n' +
    '        at file:///home/node/.cache/filecoin-station-core/sources/voyager/vendor/saturn-js-client/dist/strn.min.js:2:815683\n' +
    '        at Object.action (ext:deno_web/02_timers.js:150:11)\n' +
    '        at handleTimerMacrotask (ext:deno_web/02_timers.js:64:10)\n' +
    '        at eventLoopTick (ext:core/01_core.js:184:21)',
  cwd: '/home/node/.cache/filecoin-station-core/sources',
  failed: true,
~~~

**Comment by juliangruber** [comment]
I think all is fine, occasional exit errors can happen. If you see a specific one that is problematic, please open a new and more specific issue 🙏
